zephirperformance.lo: /work/github/zephir-performance/zephirperformance/ext/zephirperformance.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/zephirperformance.c -o zephirperformance.lo 
kernel/main.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/extended/fcall.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/extended/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/extended/fcall.c -o kernel/extended/fcall.lo 
kernel/require.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /work/github/zephir-performance/zephirperformance/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/kernel/exit.c -o kernel/exit.lo 
zephirperformance/zephirperformance.lo: /work/github/zephir-performance/zephirperformance/ext/zephirperformance/zephirperformance.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/work/github/zephir-performance/zephirperformance/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /work/github/zephir-performance/zephirperformance/ext/zephirperformance/zephirperformance.zep.c -o zephirperformance/zephirperformance.lo 
$(phplibdir)/zephirperformance.la: ./zephirperformance.la
	$(LIBTOOL) --mode=install cp ./zephirperformance.la $(phplibdir)

./zephirperformance.la: $(shared_objects_zephirperformance) $(ZEPHIRPERFORMANCE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_zephirperformance) $(ZEPHIRPERFORMANCE_SHARED_LIBADD)

